<script lang="ts">
  import { enhance } from '$app/forms';
  import { afterNavigate } from '$app/navigation';
  
  let { data, form } = $props();
  
  let copied = false;
  let formData = {
    physicalRooms: '',
    auditedBy: '',
    notes: ''
  };
  
  let result = $derived(form?.result);
  let errors = $derived(form?.errors);
  let success = $derived(form?.success);
  
  // Reset form after successful audit
  afterNavigate(() => {
    if (success) {
      formData = { physicalRooms: '', auditedBy: '', notes: '' };
    }
  });
  
  function formatCurrency(amount: number) {
    return new Intl.NumberFormat('en-NG', {
      style: 'currency',
      currency: 'NGN',
      minimumFractionDigits: 2
    }).format(amount);
  }
  
  function formatDateTime(date: Date) {
    return new Intl.DateTimeFormat('en-NG', {
      dateStyle: 'full',
      timeStyle: 'medium'
    }).format(new Date(date));
  }
  
  async function copyReport() {
    if (!result) return;
    
    const report = `
🏨 TOPGAN HOTEL MANAGEMENT SYSTEM
📋 NIGHT AUDIT REPORT
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

📅 Audit Date: ${formatDateTime(new Date())}
👤 Audited By: ${formData.auditedBy || 'N/A'}

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
📊 AUDIT RESULTS
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

✅ System Occupied Rooms: ${result.systemCount}
👥 Physical Occupied Rooms: ${result.physicalCount}
⚠️  Discrepancy: ${result.discrepancy > 0 ? '+' : ''}${result.discrepancy}

${result.flaggedRooms.length > 0 ? `
🚨 FLAGGED ROOMS:
${result.flaggedRooms.map(room => `   • Room ${room}`).join('\n')}

💰 Estimated Unrecorded Revenue: ${formatCurrency(result.unrecordedEstimate)}
` : '✅ No discrepancies found! All rooms properly recorded.'}

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
💵 FINANCIAL SUMMARY
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

Total Revenue Today: ${formatCurrency(result.totalRevenue)}
${result.discrepancy !== 0 ? `Potential Loss: ${formatCurrency(result.unrecordedEstimate)}` : ''}

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
🔒 Report generated by TOPGAN HMS
    `;
    
    await navigator.clipboard.writeText(report);
    copied = true;
    setTimeout(() => copied = false, 2000);
  }
  
  function printReport() {
    window.print();
  }
  
  function newAudit() {
    formData = { physicalRooms: '', auditedBy: '', notes: '' };
    // Clear the form result
    window.location.href = '/audit';
  }
</script>

<div class="min-h-screen bg-linear-to-br from-blue-50 to-gray-100">
  <div class="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-8">
    <!-- Header -->
    <div class="mb-8 text-center print:mb-4">
      <div class="flex justify-between items-center print:hidden">
        <button
          on:click={() => window.location.href = '/'}
          class="text-gray-600 hover:text-gray-900"
        >
          ← Back to Dashboard
        </button>
        <div class="flex gap-2">
          {#if result && success}
            <button
              on:click={copyReport}
              class="px-4 py-2 bg-gray-600 text-white rounded-lg hover:bg-gray-700 transition"
            >
              {copied ? '✓ Copied!' : '📋 Copy Report'}
            </button>
            <button
              on:click={printReport}
              class="px-4 py-2 bg-blue-600 text-white rounded-lg hover:bg-blue-700 transition"
            >
              🖨️ Print
            </button>
          {/if}
        </div>
      </div>
      
      <h1 class="text-4xl font-bold text-gray-900 mt-4">
        <span class="bg-clip-text text-transparent bg-gradient-to-r from-blue-600 to-purple-600">
          Night Audit System
        </span>
      </h1>
      <p class="text-gray-600 mt-2 text-lg">
        "The Eyes of the Owner" — Real-time discrepancy detection
      </p>
      <div class="text-sm text-gray-500 mt-1">
        {formatDateTime(new Date())}
      </div>
    </div>

    <div class="grid grid-cols-1 lg:grid-cols-2 gap-8 print:grid-cols-1">
      <!-- Audit Form -->
      <div class="bg-white rounded-xl shadow-xl p-6 print:shadow-none">
        <div class="flex items-center gap-2 mb-6">
          <div class="w-2 h-2 bg-green-500 rounded-full animate-pulse"></div>
          <h2 class="text-xl font-semibold">Run Night Audit</h2>
        </div>
        
        <form method="POST" use:enhance class="space-y-6">
          <div>
            <label class="block text-sm font-medium text-gray-700 mb-2">
              Physically Occupied Rooms *
            </label>
            <textarea
              name="physicalRooms"
              rows="4"
              class="w-full px-4 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-blue-500 focus:border-transparent font-mono"
              placeholder="Enter room numbers separated by commas&#10;Example: 101, 102, 103, 201, 202"
              bind:value={formData.physicalRooms}
              required
            ></textarea>
            {#if errors?.physicalRooms}
              <p class="text-red-600 text-xs mt-1">{errors.physicalRooms[0]}</p>
            {/if}
            <p class="text-xs text-gray-500 mt-1">
              🔍 Walk the property and list all physically occupied rooms
            </p>
          </div>

          <div>
            <label class="block text-sm font-medium text-gray-700 mb-2">
              Audited By *
            </label>
            <input
              type="text"
              name="auditedBy"
              class="w-full px-4 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-blue-500 focus:border-transparent"
              placeholder="Your name or staff ID"
              bind:value={formData.auditedBy}
              required
            />
            {#if errors?.auditedBy}
              <p class="text-red-600 text-xs mt-1">{errors.auditedBy[0]}</p>
            {/if}
          </div>

          <div>
            <label class="block text-sm font-medium text-gray-700 mb-2">
              Notes (Optional)
            </label>
            <textarea
              name="notes"
              rows="2"
              class="w-full px-4 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-blue-500 focus:border-transparent"
              placeholder="Any observations or issues noted during walk..."
              bind:value={formData.notes}
            ></textarea>
          </div>

          {#if form?.error}
            <div class="p-3 bg-red-50 border border-red-200 rounded-lg">
              <p class="text-red-600 text-sm">{form.error}</p>
            </div>
          {/if}

          <button
            type="submit"
            class="w-full bg-gradient-to-r from-blue-600 to-purple-600 text-white py-3 rounded-lg font-semibold hover:from-blue-700 hover:to-purple-700 transition transform hover:scale-[1.02]"
          >
            🔍 Run Night Audit
          </button>
        </form>
      </div>

      <!-- Results Section -->
      {#if result && success}
        <div class="space-y-6 print:mt-4">
          <!-- Audit Summary Card -->
          <div class="bg-white rounded-xl shadow-xl p-6 print:shadow-none">
            <h3 class="text-lg font-semibold mb-4 flex items-center gap-2">
              <span class="text-2xl">📊</span>
              Audit Results
            </h3>
            
            <div class="grid grid-cols-2 gap-4">
              <div class="p-3 bg-green-50 rounded-lg">
                <div class="text-sm text-gray-600">System Occupied</div>
                <div class="text-2xl font-bold text-green-700">{result.systemCount}</div>
              </div>
              <div class="p-3 bg-blue-50 rounded-lg">
                <div class="text-sm text-gray-600">Physical Count</div>
                <div class="text-2xl font-bold text-blue-700">{result.physicalCount}</div>
              </div>
            </div>
            
            <div class="mt-4 p-3 rounded-lg {result.discrepancy === 0 ? 'bg-green-50' : 'bg-red-50'}">
              <div class="text-sm text-gray-600">Discrepancy</div>
              <div class="text-2xl font-bold {result.discrepancy === 0 ? 'text-green-700' : 'text-red-700'}">
                {result.discrepancy > 0 ? '+' : ''}{result.discrepancy}
              </div>
              {#if result.discrepancy !== 0}
                <p class="text-sm text-red-600 mt-1">
                  ⚠️ {Math.abs(result.discrepancy)} room(s) occupied but not in system
                </p>
              {/if}
            </div>
          </div>

          <!-- Flagged Rooms -->
          {#if result.flaggedRooms.length > 0}
            <div class="bg-white rounded-xl shadow-xl p-6 print:shadow-none border-l-4 border-red-500">
              <h3 class="text-lg font-semibold mb-3 flex items-center gap-2">
                <span class="text-2xl">🚨</span>
                Flagged Rooms (Fraud Risk)
              </h3>
              <div class="flex flex-wrap gap-2">
                {#each result.flaggedRooms as room (room)}
                  <span class="px-3 py-1 bg-red-100 text-red-700 rounded-full font-mono font-bold">
                    Room {room}
                  </span>
                {/each}
              </div>
              <div class="mt-4 p-3 bg-yellow-50 rounded-lg">
                <p class="text-sm text-yellow-800">
                  💰 Estimated Unrecorded Revenue: <strong>{formatCurrency(result.unrecordedEstimate)}</strong>
                </p>
              </div>
            </div>
          {:else}
            <div class="bg-white rounded-xl shadow-xl p-6 print:shadow-none border-l-4 border-green-500">
              <div class="flex items-center gap-3">
                <span class="text-3xl">✅</span>
                <div>
                  <h3 class="font-semibold text-green-800">No Discrepancies Found</h3>
                  <p class="text-sm text-green-600">All occupied rooms are properly recorded in the system</p>
                </div>
              </div>
            </div>
          {/if}

          <!-- Financial Summary -->
          <div class="bg-white rounded-xl shadow-xl p-6 print:shadow-none">
            <h3 class="text-lg font-semibold mb-3 flex items-center gap-2">
              <span class="text-2xl">💰</span>
              Financial Summary
            </h3>
            <div class="space-y-2">
              <div class="flex justify-between items-center p-2 border-b">
                <span class="text-gray-600">Total Revenue Today:</span>
                <span class="text-xl font-bold text-green-600">{formatCurrency(result.totalRevenue)}</span>
              </div>
              {#if result.discrepancy !== 0}
                <div class="flex justify-between items-center p-2 bg-red-50 rounded">
                  <span class="text-red-600">Potential Loss:</span>
                  <span class="text-lg font-bold text-red-700">{formatCurrency(result.unrecordedEstimate)}</span>
                </div>
              {/if}
            </div>
          </div>

          <!-- Action Buttons -->
          <div class="flex gap-3 print:hidden">
            <button
              on:click={newAudit}
              class="flex-1 px-4 py-2 bg-gray-600 text-white rounded-lg hover:bg-gray-700 transition"
            >
              New Audit
            </button>
          </div>
        </div>
      {/if}
    </div>
  </div>
</div>

<style>
  @media print {
    .print\:hidden {
      display: none !important;
    }
    .print\:shadow-none {
      box-shadow: none !important;
    }
    .print\:mt-4 {
      margin-top: 1rem !important;
    }
    body {
      background: white;
    }
  }
</style>